"use strict";
var userAgent = navigator.userAgent.toLowerCase(),
    initialDate = new Date(),
    $document = $(document),
    $window = $(window),
    handler = "/search";
    $html = $("html"),
    isDesktop = $html.hasClass("desktop"),
    isIE = userAgent.indexOf("msie") != -1 ? parseInt(userAgent.split("msie")[1]) : userAgent.indexOf("trident") != -1 ? 11 : userAgent.indexOf("edge") != -1 ? 12 : false,
    isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),
    isTouch = "ontouchstart" in window,
    plugins = {
        pointerEvents: isIE < 11 ? "js/pointer-events.min.js" : false,
        bootstrapTooltip: $("[data-toggle='tooltip']"),
        bootstrapTabs: $(".tabs"),
        bootstrapAccordions: $(".accordion"),
        rdParallax: $(".rd-parallax"),
        rdGoogleMaps: $(".rd-google-map"),
        rdNavbar: $(".rd-navbar"),
        mfp: $('[data-lightbox]').not('[data-lightbox="gallery"] [data-lightbox]'),
        mfpGallery: $('[data-lightbox^="gallery"]'),
        owl: $(".owl-carousel"),
        swiper: $(".swiper-slider"),
        counter: $(".counter"),
        twitterfeed: $(".twitter"),
        progressBar: $(".progress-bar-js"),
        isotope: $(".isotope"),
        countDown: $(".countdown"),
        popover: $('[data-toggle="popover"]'),
        dateCountdown: $('.DateCountdown'),
        statefulButton: $('.btn-stateful'),
        slick: $('.slick-slider'),
        viewAnimate: $('.view-animate'),
        selectFilter: $("select"),
        rdInputLabel: $(".form-label"),
        bootstrapDateTimePicker: $("[data-time-picker]"),
        customWaypoints: $('[data-custom-scroll-to]'),
        photoSwipeGallery: $("[data-photo-swipe-item]"),
        stepper: $("input[type='number']"),
        radio: $("input[type='radio']"),
        checkbox: $("input[type='checkbox']"),
        customToggle: $("[data-custom-toggle]"),
        rdMailForm: $(".rd-mailform"),
        regula: $("[data-constraints]"),
        pageLoader: $(".page-loader"),
        search: $(".rd-search"),
        searchResults: $('.rd-search-results'),
        imgZoom: $('[mag-thumb]'),
        pageTitles: $('.page-title')
    };  